In [2]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
import sys
from pathlib import Path
import os
import pandas as pd
import numpy as np
import re

PROJECT_ROOT = Path.cwd().parents[0]
SRC_PATH = PROJECT_ROOT / "src"
sys.path.append(str(SRC_PATH))  

from MicroNAV.adapters.outbound.db.sqlite_db import Db_datos


from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[0]
DB_PATH = PROJECT_ROOT / "data" / "microvap.db"
DATA_RAW = PROJECT_ROOT / "data" / "raw"

db_data = Db_datos(DB_PATH) # Instanciar la clase: No puedo usar el carro directamente, debo clonarlo.

c:\Users\ingridbumo\OneDrive - Universidad de la Sabana\Escritorio\Documentos Organizados\TSID-CCM\Python-Jonathan\Modelo Analitica\data\microvap.db

In [5]:
sql = """Select * From patient;  """
df_patient = db_data.extracData(sql)

In [6]:
df_patient.describe()

,patient_id,gender,alcoholism,anemia,stroke,asthma,cancer,diabetes,coronary_heart_disease,mental_illness,...,copd,heart_failure,hemodialysis,hypertension,ppi_chronic,obesity,sahos,smoking,statin,no_background
count,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000,...,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000
mean,155.635714,0.657143,0.064286,0.014286,0.042857,0.014286,0.021429,0.085714,0.028571,0.014286,...,0.021429,0.021429,0.014286,0.328571,0.007143,0.035714,0.007143,0.064286,0.007143,0.500000
std,89.975633,0.476369,0.246142,0.119092,0.203262,0.119092,0.145328,0.280947,0.167197,0.119092,...,0.145328,0.145328,0.119092,0.471380,0.084515,0.186243,0.084515,0.246142,0.084515,0.501795
min,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,73.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,172.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000
75%,227.250000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,299.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [10]:
sql1 = """select * 
from patient 
inner join 
admission 
on patient.patient_id = admission.patient_id 
order by patient.patient_id"""
df_patient1 = db_data.extracData(sql1)
df_patient1.head()

,patient_id,gender,height,weight,alcoholism,anemia,stroke,asthma,cancer,diabetes,...,admission_general_surgery,admission_cardiovascular,admission_trauma,admission_nephrological,admission_neurological,admission_neurosurgical,admission_autoimmune,admission_toxic,admission_metabolic,other_diagnostic_admission
0,6,1,163,70,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,11,1,167,60,0,0,1,0,0,1,...,0,1,0,0,0,0,0,0,0,0
2,12,1,170,74,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,17,1,165,70,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,18,0,163,50,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [14]:
sql2 = """select cancer, count(cancer) as number_patient from patient group by cancer;"""
df_patient2 = db_data.extracData(sql2)
df_patient2.head()

   cancer  number_patient
0       0             137
1       1               3

In [15]:
import plotly.express as px
# This dataframe has 244 lines, but 4 distinct values for `day`
fig = px.pie(df_patient2, values='number_patient', names='cancer')
fig.show()